create extension if not exists pgcrypto;

create table if not exists public.certification_sections (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint certification_sections_code_check
    check (code in ('CORE', 'TYPE_I', 'TYPE_II', 'TYPE_III'))
);

alter table public.certification_sections
  add column if not exists description text;

alter table public.certification_sections
  add column if not exists sort_order integer not null default 0;

alter table public.certification_sections
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.certification_sections
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create table if not exists public.topics (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.certification_sections (id) on delete cascade,
  code text not null,
  name text not null,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint topics_section_code_unique unique (section_id, code)
);

alter table public.topics
  add column if not exists description text;

alter table public.topics
  add column if not exists sort_order integer not null default 0;

alter table public.topics
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.topics
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  section_id uuid references public.certification_sections (id) on delete restrict,
  topic_id uuid references public.topics (id) on delete set null,
  question_text text,
  explanation text,
  difficulty text not null default 'medium',
  reference text,
  version integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint questions_difficulty_check
    check (difficulty in ('easy', 'medium', 'hard')),
  constraint questions_version_check
    check (version >= 1)
);

alter table public.questions
  add column if not exists public_id uuid not null default gen_random_uuid();

alter table public.questions
  add column if not exists section_id uuid references public.certification_sections (id) on delete restrict;

alter table public.questions
  add column if not exists topic_id uuid references public.topics (id) on delete set null;

alter table public.questions
  add column if not exists question_text text;

alter table public.questions
  add column if not exists explanation text;

alter table public.questions
  add column if not exists difficulty text not null default 'medium';

alter table public.questions
  add column if not exists reference text;

alter table public.questions
  add column if not exists version integer not null default 1;

alter table public.questions
  add column if not exists is_active boolean not null default true;

alter table public.questions
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.questions
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists idx_questions_public_id
  on public.questions (public_id);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'questions'
      and column_name = 'question'
  ) then
    execute '
      update public.questions
      set question_text = coalesce(question_text, question)
      where question_text is null
    ';
  end if;
end
$$;

do $$
declare
  question_id_type text;
begin
  select c.data_type
  into question_id_type
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'questions'
    and c.column_name = 'id';

  if question_id_type = 'bigint' then
    execute '
      create table if not exists public.question_choices (
        id uuid primary key default gen_random_uuid(),
        question_id bigint not null references public.questions (id) on delete cascade,
        choice_text text not null,
        is_correct boolean not null default false,
        sort_order integer not null default 0,
        created_at timestamptz not null default timezone(''utc'', now()),
        updated_at timestamptz not null default timezone(''utc'', now())
      )
    ';
  else
    execute '
      create table if not exists public.question_choices (
        id uuid primary key default gen_random_uuid(),
        question_id uuid not null references public.questions (id) on delete cascade,
        choice_text text not null,
        is_correct boolean not null default false,
        sort_order integer not null default 0,
        created_at timestamptz not null default timezone(''utc'', now()),
        updated_at timestamptz not null default timezone(''utc'', now())
      )
    ';
  end if;
end
$$;

alter table public.question_choices
  add column if not exists sort_order integer not null default 0;

alter table public.question_choices
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.question_choices
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create or replace function public.set_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_certification_sections_updated_at on public.certification_sections;
create trigger set_certification_sections_updated_at
before update on public.certification_sections
for each row
execute function public.set_timestamp_updated_at();

drop trigger if exists set_topics_updated_at on public.topics;
create trigger set_topics_updated_at
before update on public.topics
for each row
execute function public.set_timestamp_updated_at();

drop trigger if exists set_questions_updated_at on public.questions;
create trigger set_questions_updated_at
before update on public.questions
for each row
execute function public.set_timestamp_updated_at();

drop trigger if exists set_question_choices_updated_at on public.question_choices;
create trigger set_question_choices_updated_at
before update on public.question_choices
for each row
execute function public.set_timestamp_updated_at();

create index if not exists idx_topics_section_sort
  on public.topics (section_id, sort_order);

create index if not exists idx_questions_section_active
  on public.questions (section_id, is_active);

create index if not exists idx_questions_topic_active
  on public.questions (topic_id, is_active);

create index if not exists idx_question_choices_question_sort
  on public.question_choices (question_id, sort_order);

alter table public.certification_sections enable row level security;
alter table public.topics enable row level security;
alter table public.questions enable row level security;
alter table public.question_choices enable row level security;

drop policy if exists "Authenticated users can read certification sections" on public.certification_sections;
create policy "Authenticated users can read certification sections"
on public.certification_sections
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read topics" on public.topics;
create policy "Authenticated users can read topics"
on public.topics
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read active questions" on public.questions;
create policy "Authenticated users can read active questions"
on public.questions
for select
to authenticated
using (is_active = true);

drop policy if exists "Authenticated users can read choices for active questions" on public.question_choices;
create policy "Authenticated users can read choices for active questions"
on public.question_choices
for select
to authenticated
using (
  exists (
    select 1
    from public.questions
    where public.questions.id = question_choices.question_id
      and public.questions.is_active = true
  )
);
